version: "3"

volumes:
    shared_volume:

services:
    nlpdeploy:
        build: .
        container_name: nlpdeploy
        stdin_open: true
        tty: true
        ports:
            - 5000:5000
        volumes:
            - shared_volume:/app/models
            - .:/python
